
<!-- meta tags and other links -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="csrf-token" content="EpA8f7Gx3Ge4XPgJ7ZpD6I0lpqmvArzFQwNKAhC9">
  <title>Primevests - Two Factor</title>
    <meta name="description" content="become a private lender on SeedGate and make huge returns for the rest of the year investing in real estate and Metaverse.">
    <meta name="keywords" content="TRADING,MAKING MONEY,NFTs,Metaverse,primevests,investment">
    <link rel="shortcut icon" href="https://primevests.com/account/assets/images/logoIcon/favicon.png" type="image/x-icon">

    
    <link rel="apple-touch-icon" href="https://primevests.com/account/assets/images/logoIcon/logo.png">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Primevests - Two Factor">
    
    <meta itemprop="name" content="Primevests - Two Factor">
    <meta itemprop="description" content="">
    <meta itemprop="image" content="https://primevests.com/account/assets/images/seo/63cc7c80269ff1674345600.png">
    
    <meta property="og:type" content="website">
    <meta property="og:title" content="SEEDGATE- Alternative Investment option">
    <meta property="og:description" content="Introducing the first marketplace for investing in real estate debt and metaverse properties. Now you can invest in the loans made to borrowers(real estate agencies), and as they pay back their loans, you make money.And also co-own properties in the metaverse and NFTs.">
    <meta property="og:image" content="https://primevests.com/account/assets/images/seo/63cc7c80269ff1674345600.png"/>
    <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="600" />
    <meta property="og:image:height" content="315" />
    <meta property="og:url" content="https://primevests.com/account/user/twofactor">
    
    <meta name="twitter:card" content="summary_large_image">
  <!-- bootstrap 4  -->

  
  
  <link rel="stylesheet" href="https://primevests.com/account/assets/templates/dashlite//css/dashlite.css?ver=2.4.0">
  <link rel="stylesheet" href="https://primevests.com/account/assets/templates/dashlite//css/theme.css?ver=2.4.0">
  

  </head>

<body class="nk-body npc-invest bg-lighter no-touch  as-mobile">
  <div class="nk-app-root">
        <!-- wrap @s  -->
    <div class="nk-wrap ">
      <div class="nk-header nk-header-fluid is-theme">
        <div class="container-xl wide-xl">
          <div class="nk-header-wrap">
            <div class="nk-menu-trigger mr-sm-2 d-lg-none">
              <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="headerNav"><em
                  class="icon ni ni-menu"></em></a>
            </div>
            <div class="nk-header-brand">
              <a href="https://primevests.com/account" class="logo-link">
                <img class="logo-light logo-img" src="https://primevests.com/account/assets/images/logoIcon/logo.png"
                  srcset="https://primevests.com/account/assets/images/logoIcon/logo.png 2x" alt="logo">
                <img class="logo-dark logo-img" src="https://primevests.com/account/assets/images/logoIcon/logo.png"
                  srcset="https://primevests.com/account/assets/images/logoIcon/logo.png 2x" alt="logo-dark">
              </a>
            </div><!-- .nk-header-brand -->
            <div class="nk-header-menu" data-content="headerNav">
              <div class="nk-header-mobile">
                <div class="nk-header-brand">
                  <a href="https://primevests.com/account" class="logo-link">
                    <img class="logo-light logo-img"
                      src="https://primevests.com/account/assets/images/logoIcon/logo.png"
                      srcset="https://primevests.com/account/assets/images/logoIcon/logo.png 2x" alt="logo">
                    <img class="logo-dark logo-img"
                      src="https://primevests.com/account/assets/images/logoIcon/logo.png"
                      srcset="https://primevests.com/account/assets/images/logoIcon/logo.png 2x" alt="logo-dark">
                  </a>
                </div>
                <div class="nk-menu-trigger mr-n2">
                  <a href="#" class="nk-nav-toggle nk-quick-nav-icon" data-target="headerNav"><em
                      class="icon ni ni-arrow-left"></em></a>
                </div>
              </div>
              <ul class="nk-menu nk-menu-main ui-s2">
                <li class="nk-menu-item">
                  <a href="https://primevests.com/account/user/dashboard" class="nk-menu-link">
                    <span class="nk-menu-text">Dashboard</span>
                  </a>
                </li><!-- .nk-menu-item -->
                <li class="nk-menu-item">
                  <a href="https://primevests.com/account/user/plan" class="nk-menu-link">
                    <span class="nk-menu-text">Investment</span>
                  </a>
                </li><!-- .nk-menu-item -->
                <li class="nk-menu-item">
                  <a href="https://primevests.com/account/user/withdraw" class="nk-menu-link">
                    <span class="nk-menu-text">Withdraw</span>
                  </a>
                </li><!-- .nk-menu-item -->
                <li class="nk-menu-item">
                  <a href="https://primevests.com/account/user/deposit" class="nk-menu-link">
                    <span class="nk-menu-text">Deposit</span>
                  </a>
                </li><!-- .nk-menu-item -->
                <li class="nk-menu-item">
                  <a href="https://primevests.com/account/user/transactions/deposit-wallet" class="nk-menu-link">
                    <span class="nk-menu-text">Transactions</span>
                  </a>
                </li><!-- .nk-menu-item -->
                <li class="nk-menu-item has-sub">
                  <a href="#" class="nk-menu-link nk-menu-toggle">
                    <span class="nk-menu-text">Referrals</span>
                  </a>
                  <ul class="nk-menu-sub">
                    <li class="nk-menu-item">
                      <a href="https://primevests.com/account/user/referral/users" class="nk-menu-link"><span
                          class="nk-menu-text">Referred Users</span></a>
                    </li>
                    <li class="nk-menu-item">
                      <a href="https://primevests.com/account/user/referral/commissions/deposit" class="nk-menu-link"><span
                          class="nk-menu-text">Referral Commisions</span></a>
                    </li>
                  </ul><!-- .nk-menu-sub -->
                </li><!-- .nk-menu-item -->


              </ul><!-- .nk-menu -->
            </div><!-- .nk-header-menu -->
            <div class="nk-header-tools">
              <ul class="nk-quick-nav">
                <li class="dropdown user-dropdown order-sm-first">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <div class="user-toggle">
                      <div class="user-avatar sm">
                        <em class="icon ni ni-user-alt"></em>
                      </div>
                      <div class="user-info d-none d-xl-block">
                        
                        <div class="user-name dropdown-indicator">Henry Beth
                        </div>
                      </div>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-md dropdown-menu-right dropdown-menu-s1 is-light">
                    <div class="dropdown-inner user-card-wrap bg-lighter d-none d-md-block">
                      <div class="user-card">
                        <div class="user-avatar">
                          <span>AB</span>
                        </div>
                        <div class="user-info">
                          <span class="lead-text">Henry Beth</span>
                          <span class="sub-text">joshdjosh6@gmail.com</span>
                        </div>
                        <div class="user-action">
                          <a class="btn btn-icon mr-n2" href="https://primevests.com/account/user/profile-setting"><em
                              class="icon ni ni-setting"></em></a>
                        </div>
                      </div>
                    </div>
                    <div class="dropdown-inner user-account-info">
                      <h6 class="overline-title-alt">Interest Balance</h6>
                      <div class="user-balance">0.00 <small
                          class="currency currency-usd">GBP</small></div>
                      <div class="user-balance-sub">
                        Locked <span>0.00
                          <span class="currency currency-usd">GBP</span></span>
                      </div>
                      <a href="https://primevests.com/account/user/withdraw" class="link">
                        <span>Withdraw Balance</span> <em class="icon ni ni-wallet-out"></em>
                      </a>
                    </div>
                    <div class="dropdown-inner">
                      <ul class="link-list">

                        <li>
                          <a href="https://primevests.com/account/user/profile-setting">
                            <em class="icon ni ni-user-alt"></em>Profile Setting                          </a>
                        </li>
                                                <li>
                          <a href="https://primevests.com/account/user/change-password">
                            <em class="icon ni ni-lock"></em>Change Password                          </a>
                        </li>
                        <li>
                          <a href="https://primevests.com/account/ticket">
                            <em class="icon ni ni-info"></em>Support Ticket                          </a>
                        </li>
                        <li>
                          <a href="https://primevests.com/account/user/promotional-tool">
                            <em class="icon ni ni-gift"></em>Promotional Tool                          </a>
                        </li>
                        <li>
                          <a href="https://primevests.com/account/user/twofactor">
                            <em class="icon ni ni-lock"></em>2FA Security                          </a>
                        </li>

                        <li>
                          <a class="dark-switch" href="#"><em class="icon ni ni-moon"></em><span>Dark Mode</span></a>
                        </li>
                      </ul>
                    </div>
                    <div class="dropdown-inner">
                      <ul class="link-list">
                        <li>
                          <a href="https://primevests.com/account/logout">
                            <em class="icon ni ni-signout"></em><span>Sign Out</span>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </li><!-- .dropdown -->
              </ul><!-- .nk-quick-nav -->
            </div><!-- .nk-header-tools -->
          </div><!-- .nk-header-wrap -->
        </div><!-- .container-fliud -->
      </div>
      <!-- main header @e  -->





        
  <div class="nk-content nk-content-lg nk-content-fluid">
    <div class="container-xl wide-lg">
      <div class="nk-content-inner">
        <div class="nk-content-body">
          <div class="nk-block-head text-center">
            <div class="nk-block-head-content">
              <div class="nk-block-head-content">
                <h2 class="nk-block-title fw-normal">Two Factor</h2>
              </div>
            </div>
          </div><!-- nk-block -->
          <div class="nk-block">



            <div class="row dashboard-content">
              <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="dashboard-inner-content">

                  <div class="row">


                    <div class="col-lg-6 col-md-6">
                                              <div class="card card-bordered">

                          <h5 class="card-header">Two Factor Authenticator</h5>
                          <div class="card-body">
                            <div class="form-group">
                              <div class="input-group">
                                <input type="text" name="key" value="QQPUJMTY2NO2ZHAJ"
                                  class="form-control form-control-lg" id="referralURL" readonly>
                                <div class="input-group-append">
                                  <span class="input-group-text copytext copyBoard" id="copyBoard" onclick="myFunction()">
                                    <i class="fa fa-copy"></i> </span>
                                </div>
                              </div>
                            </div>
                            <div class="form-group mx-auto text-center">
                              <img class="mx-auto" src="https://chart.googleapis.com/chart?chs=200x200&amp;chld=M|0&amp;cht=qr&amp;chl=otpauth%3A%2F%2Ftotp%2FHenrybeth%40Primevests%3Fsecret%3DQQPUJMTY2NO2ZHAJ">
                            </div>
                            <div class="form-group mx-auto text-center">

                              <a href="#0" class="btn btn-lg mt-3 mb-1 cmn-btn btn-primary" data-toggle="modal"
                                data-target="#enableModal">Enable Two Factor Authenticator</a>
                            </div>

                          </div>
                        </div>

                                          </div>

                    <div class="col-lg-6 col-md-6">
                      <div class=" card card-bordered">
                        <h5 class="card-header">Google Authenticator</h5>
                        <div class=" card-body">
                          <h5 class="text-uppercase">Use Google Authenticator to Scan the QR code or use the code                          </h5>
                          <hr />
                          <p>Google Authenticator is a multifactor app for mobile devices. It generates timed codes
                            used during the 2-step verification process. To use Google Authenticator, install the Google
                            Authenticator application on your mobile device.</p>
                          <a class="btn btn-md mt-3 cmn-btn btn-primary"
                            href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en"
                            target="_blank">DOWNLOAD APP</a>
                        </div>
                      </div><!-- //. single service item -->
                    </div>

                  </div>
                </div>
              </div>
            </div>



            <!--Enable Modal -->
            <div id="enableModal" class="modal fade" role="dialog">
              <div class="modal-dialog ">
                <!-- Modal content-->
                <div class="modal-content modal-content-bg">
                  <div class="modal-header">
                    <h4 class="modal-title">Verify your OTP</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                  <form action="https://primevests.com/account/user/twofactor/enable" method="POST" class="register">
                    <input type="hidden" name="_token" value="EpA8f7Gx3Ge4XPgJ7ZpD6I0lpqmvArzFQwNKAhC9">                    <div class="modal-body ">
                      <div class="form-group">
                        <input type="hidden" name="key" value="QQPUJMTY2NO2ZHAJ">
                        <input type="text" class="form-control" name="code"
                          placeholder="Enter Google Authenticator Code">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger action-btn" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary action-btn">Verify</button>
                    </div>
                  </form>
                </div>

              </div>
            </div>

            <!--Disable Modal -->
            <div id="disableModal" class="modal fade" role="dialog">
              <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content modal-content-bg">
                  <div class="modal-header">
                    <h4 class="modal-title">Verify your OTP disable</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>
                  <form action="https://primevests.com/account/user/twofactor/disable" method="POST" class="register">
                    <input type="hidden" name="_token" value="EpA8f7Gx3Ge4XPgJ7ZpD6I0lpqmvArzFQwNKAhC9">                    <div class="modal-body">
                      <div class="form-group">
                        <input type="text" class="form-control" name="code"
                          placeholder="Enter Google Authenticator Code">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger action-btn" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary action-btn">Verify</button>
                    </div>
                  </form>
                </div>

              </div>
            </div>



          </div>
        </div>
      </div>
    </div>
  </div>


      

      
      <!-- footer @s  -->
      <div class="nk-footer nk-footer-fluid bg-lighter">
        <div class="container-xl wide-lg">
          <div class="nk-footer-wrap">
            <div class="nk-footer-copyright">
              © 2023 <a href="https://primevests.com/account">Primevests</a>. All rights reserved            </div>
            <div class="nk-footer-links">
              <ul class="menu">
								<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1033"><a href="#">Terms & Condition</a></li>
								<li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1034"><a href="#">Privacy Policy</a></li>
            </div>
          </div>
        </div>
      </div>
      <!-- footer @e  -->
    </div> <!-- page-wrapper end -->
  </div>
  

  <script src="https://primevests.com/account/assets/templates/dashlite//js/bundle.js?ver=2.4.0"></script>
  <script src="https://primevests.com/account/assets/templates/dashlite//js/scripts.js?ver=2.4.0"></script>
  <script src="https://primevests.com/account/assets/templates/dashlite//js/charts/chart-invest.js?ver=2.4.0"></script>


  <link rel="stylesheet" href="https://primevests.com/account/assets/templates/dashlite/css/iziToast.min.css">
<script src="https://primevests.com/account/assets/templates/dashlite/js/iziToast.min.js"></script>

            <script type="text/javascript">
            "use strict";
            iziToast.error({message:"Wrong Verification Code", position: "topRight"});
        </script>
    
<script>
"use strict";
    function notify(status,message) {
        iziToast[status]({
            message: message,
            position: "topRight"
        });
    }
</script>


  
    <script>
    $('.copyBoard').click(function() {
      "use strict";
      var copyText = document.getElementById("referralURL");
      copyText.select();
      copyText.setSelectionRange(0, 99999);
      /*For mobile devices*/
      document.execCommand("copy");
      iziToast.success({
        message: "Copied: " + copyText.value,
        position: "topRight"
      });
    });
  </script>

  <script>
    (function() {
      "use strict";
      $(document).on("change", ".langSel", function() {
        window.location.href = "https://primevests.com/account/change/" + $(this).val();
      });
    })();
  </script>

</body>

</html>
